### ISSUE TITLE
what will be type is i want to create notification with new transactions

### ISSUE THREAD

**Issue by ishwarchandratiwari** [BlockIo/block_io-nodejs#12]
block_io.create_notification({'type': 'new-transactions', 'url': 'YOUR URL'}, console.log);

when is hit this module its showing ERROR:
==>Error: Must specify a valid type of events to watch.
................................................................................................
what will be type is i want to create notification with new transactions,i used type=new-transactions
but i got =>Error: Must specify a valid type of events to watch.
...block_io.create_notification({'type': 'new-transactions', 'url': 'http://13.12.118.65:3000/getReq'}, console.log);

**Comment by doersf** [comment]
Type=new-transactions are not available. People confuse it with what they actually need: type=account.
