### ISSUE TITLE
one to many, many to one payments

### ISSUE THREAD

**Issue by aidaskeburys** [BlockIo/block_io-nodejs#18]
Hello there,

My case is that each user is assigned a wallet address, and every month I want to take subscription fee. To save on fess I would like to group transactions so I could specify sending addresses and amounts.

For e.g:

sending_addresses:user_1_wallet,user_2_wallet,user_3_wallet
amounts: 0.1,0.2,0.5
receiving_addresses: main_service_wallet

problem is that you can't have multiple amounts specified and only one unique destination, but at the same point, I can't have 3 identical destinations.

This means that I have to make 3 separate transactions. Can someone suggest solution for this using block.io.

Thank you

**Comment by doersf** [comment]
The amounts are what you want to send to destination 1, 2, 3, ..., not the source addresses.

If you say from_addresses=X1,X2, amounts=A1,A2, to_address=T1,T2, then you are saying "send A1 to T1, A2 to T2". You cannot specify exactly amounts to use from each from_address; you will create separate transactions for that behavior.

**Comment by aidaskeburys** [comment]
Is there are any plans to implement functionality that would allow to take specific amounts from specific from addresses to one to_address? 

This way it would be possible to collect payments from multiple users using one transaction, rather spamming the network with multiple transactions to single address.

This could be achieved simply by allowing multiple repetitive to_addresses, instead of enforcing unique to_addresses.

for e.g.:
block_io.withdraw_from_addresses({
'amounts': 'AMOUNT1,AMOUNT2,...',
'from_addresses': 'ADDRESS1,ADDRESS2,...',
'to_addresses': 'system_wallet_address,system_wallet_address,...'}, 
console.log);

in this case in single call I could collect all payments, at the moment this give error that to_addresses must be unique.

**Comment by doersf** [comment]
I understand. This would require specification of an address which will be responsible for paying the network fees. Look out for it in V3, but we don't have an ETA yet.

**Comment by aidaskeburys** [comment]
On the same note, it would be really handy to have option to include fee into amount itself, so receiver gets amount specified - fees.  At the moment, I have to run fee_estimate on each request and and minus it from the amount that will be sent.

Thanks for reply, hopefully v3 won't take to long to roll out.
