### ISSUE TITLE
Web sockets and testnets?

### ISSUE THREAD

**Issue by ekkis** [BlockIo/block_io-nodejs#22]
I came across this https://github.com/BlockIo/block_io-nodejs/issues/8 and I'm a little further for it, but how do I get transaction information for testnets from the web sockets? is there a different url, or some way to indicate to the socket which network I want info for?

**Comment by ekkis** [comment]
why was this closed without resolution?

**Comment by doersf** [comment]
This is irrelevant to the library. For support, please use block.io/contacts or just email support@block.io.

For documentation on websockets, see block.io/docs/notifications.
