### ISSUE TITLE
localhost connection error

### ISSUE THREAD

**Issue by volo723** [BlockIo/block_io-nodejs#28]
installed "block_io": "^3.0.5" in node 12.0v and 10.9v.

and I used this code.

const BlockIo = require('block_io');
const block_io = new BlockIo(process.env.MULTISEND_BTC_BLOCKIO_KEY);

block_io.get_balance()
      .then(data => {
        console.log(JSON.stringify(data));
        res.status(200).send(JSON.stringify(data));
      }
      )
      .catch(error => {
        console.log("Error:", error.message);
        res.status(200).send(error.message);
      }
      );

    block_io.get_balance((error, data) => {
      if (error) return console.log("Error:", error.message);
      console.log(JSON.stringify(data));
    });

btw, there is such error in my local machine.{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443}

and in my test server(https).
Error: URL is not defined
Error: URL is not defined

When I use block_io@2.0.3
let balance = await block_io.get_balance();
    console.log(balance);

it returns "undefined"

**Comment by doersf** [comment]
You will want to use NodeJS 10+. Use the library's v4.0.0 and see the examples/ folder for demonstrations.
