### ISSUE TITLE
Create and sign transaction function references this.keys which is undefined

### ISSUE THREAD

**Issue by mackbjon** [BlockIo/block_io-nodejs#29]
When I take the response data from `prepare_transaction` and use it as the input for `create_and_sign_transaction`, I get an error when the block_io library attempts to find the existence of a key in `this.keys`. This occurs as `this.key` has not yet been defined. 

A workaround is to initialize block_io with a config object, rather than a string as this explicitly sets `this.keys` equal to an empty object.

**Comment by doersf** [comment]
Can you point out the line in lib/block_io.js? Is this for v4.0.1?

**Comment by mackbjon** [comment]
https://github.com/BlockIo/block_io-nodejs/blob/c7b2c8ba293b62b4ec5dcc9a935c12a58d4abe5d/lib/block_io.js#L174

**Comment by doersf** [comment]
How are you instantiating the library? What arguments are you passing to create_and_sign_transaction ? No need to provide the values of params, and definitely no sensitive data.

**Comment by doersf** [comment]
You would encounter that error if you instantiated the object using just the API Key as a string, no dictionaries/hashes.

v4.0.2 will be pushed live as a fix shortly.

**Comment by doersf** [comment]
Should be fixed in https://github.com/BlockIo/block_io-nodejs/releases/tag/4.0.2.
